### ISSUE TITLE
mystery function in WF2

### ISSUE THREAD

**Issue by diatomsRcool** [ncats/translator-modules#18]
I'm at the hackathon, trying to run WF2. I'm getting an error for the line

output = output_file(disease_associated_gene_set.get_input_disease_name(), title, "html")

in WF_automation.py

It's not finding the get_input_disease_name() function.

Same problem for get_input_disease_id()

**Comment by RichardBruskiewich** [comment]
I think you mean the  **WF2_automation.py** script.  Sorry I didn't review these issues early on in the hackathon.  

**WF2_automation.py** is actually a legacy script which has lagged in updating to follow the latest **ncats/translator-modules**  changes.    

At the hackathon, we've mainly focused on getting all the individual modules normalized and properly executable individually on the command line and in Common Workflow Language (CWL) workflows.   We can attempt to fix this and related issues now.
