### ISSUE TITLE
module to "walk" the graph

### ISSUE THREAD

**Issue by diatomsRcool** [ncats/translator-modules#19]
hackathon topic

It would be really helpful to have a module that takes two nodes and finds the ways they are connected. There are graph algorithms that do this. This could get out of hand fast. We have to be able to let the user set a ceiling for number of steps and remove any recursive connections.

**Comment by RichardBruskiewich** [comment]
Interesting commentary in that it echoes your use of the word "node" from issue #18.

It should be mentioned that the translator-modules project doesn't have knowledge graphs per say as a focal point.  However,  the various modules are now being marked up  with BIolink Model metadata aiming to tag the input and outputs of the modules as kinds of *subject-predicate-object* knowledge assertions for possible loading into a knowledge graph, which could be traversed in the manner you suggest.  

 If the Translator Modules and associated workflows are wrapped with the [NCATS Reasoner API](https://github.com/NCATS-Tangerine/NCATS-ReasonerStdAPI), then perhaps, direct dynamic navigation of the  "generated" knowledge of the Translator Modules workflows could be attempted.

In the spirit of the above, I will close this issue for now, but feel free to reopen it if you feel I've misunderstood the ideas behind your post.
