### ISSUE TITLE
Prototype Common Workflow Language (CWL) Implementation of Translator Workflow 2

### ISSUE THREAD

**Issue by RichardBruskiewich** [ncats/translator-modules#2]
We wish to convert our WF2_automation.py implementation into a CWL-operated workflow.

**Comment by kbruskiewicz** [comment]
https://github.com/ncats/translator-modules/commit/6e2fd836a29b78ab5e3870bedcfe299381ecdfd2

**Comment by kbruskiewicz** [comment]
Excludes OHSU modules though.

**Comment by RichardBruskiewich** [comment]
That is OK. The main point of this issue was to get to first base with the design pattern of using CWL. That we have done with great satisfaction. Thanks @kbruskiewicz !!!
