### ISSUE TITLE
chemical_gene_interaction uses HGNC identifiers, not ENSG

### ISSUE THREAD

**Issue by jaeddy** [ncats/translator-modules#24]
Need to update example in [README](https://github.com/ncats/translator-modules/blob/master/translator_modules/gene/chemical_substance/README.md).

**Comment by RichardBruskiewich** [comment]
Actually, this script expects NCBIGene IDs. The script was itself was split into two: **gene_to_chemical_interaction.py** which takes such gene  IDs, and **chemical_to_gene_interaction.py** which takes CTD chemical IDs and  outputs NCBIGene IDs. The scripts were working by  the end of the Hackathon, with updated READMEs.
