### ISSUE TITLE
Each translator module needs to be tested with README examples

### ISSUE THREAD

**Issue by RichardBruskiewich** [ncats/translator-modules#27]
Our objective here is to confirm whether  or not each translator module works using the sample CLI execution parameters provided in the output datatype directory README  files.

Here is an inventory of Biolink data type categories processed with their associated modules to be checked (see also **[indexed inventory of scripts](https://github.com/ncats/translator-modules/blob/master/README.md#how-the-modules-are-indexed))**:

- [ ] A checked  box below implies a working script with a working example documented in the appropriate README

### anatomical entity

- [ ] tissue_to_tissue_bicluster

### gene

- [ ] tissue_to_gene_bicluster

### gene

- [x] chemical_to_gene_interaction

### gene

- [x] disease_associated_genes

### phenotypic feature

- [ ] disease_to_phenotype_bicluster

### anatomical entity

- [x] gene_to_tissue_bicluster

### chemical_substance

- [x] gene_to_chemical_interaction

### gene

- [x] functional_similarity

- [x] gene_interaction

- [x] gene_to_gene_bicluster_RNAseqDB

- [x] gene_to_gene_bicluster_DepMap

- [x] phenotype_similarity

### disease

- [x] phenotype_to_disease_bicluster

**Comment by realmarcin** [comment]
closed, no longer relevant

**Comment by RichardBruskiewich** [comment]
okie, dokie
